version: "3"

services: 
  api:
    build: .
    restart: always
    depends_on: 
      - database
    ports: 
      - 80:1337
    volumes:
      - /tmp/energia-db/db:/data/db
  
  database:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=energia
      - MONGO_INITDB_ROOT_PASSWORD=energia-public
      - MONGO_INITDB_DATABASE=energia-db
    restart: always